# Generated by Django 2.2.7 on 2019-12-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20191214_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicename',
            name='features',
            field=models.TextField(blank=True, null=True, verbose_name='Блок с цифрами. Элементы разделяются точкой с запятой, элемент состоит из заголовка и описания. Заголовок и описание разделяются дефисом'),
        ),
        migrations.AlterField(
            model_name='servicename',
            name='imageHeader',
            field=models.ImageField(blank=True, null=True, upload_to='services_img/', verbose_name='Изображение для бекграунда страницы с услугой (1920х560)'),
        ),
    ]
