# Generated by Django 2.2.7 on 2019-12-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20191214_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSpecialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=40, null=True, verbose_name='ФИО ')),
                ('work', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('image', models.ImageField(null=True, upload_to='service_img/', verbose_name='Фото (400 x 340)')),
                ('description', models.TextField(null=True, verbose_name='Описание специплиста (примерно 50 слов)')),
            ],
        ),
        migrations.AddField(
            model_name='servicename',
            name='specialist',
            field=models.ManyToManyField(blank=True, related_name='service_spec', to='pages.ServiceSpecialist', verbose_name='Отображаемые специалисты'),
        ),
    ]
