# Generated by Django 2.2.7 on 2019-12-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20191214_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicespecialist',
            options={'verbose_name': 'Специалист', 'verbose_name_plural': 'Специалисты'},
        ),
        migrations.AddField(
            model_name='servicename',
            name='page_h2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок блока приемущества'),
        ),
    ]
