# Generated by Django 2.2.7 on 2019-12-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20191216_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicename',
            name='features',
            field=models.TextField(blank=True, null=True, verbose_name='Блок с цифрами. Элементы разделяются точкой с запятой'),
        ),
    ]
