# Generated by Django 2.2.7 on 2019-12-14 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20191214_1516'),
        ('blog', '0003_auto_20191119_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.ServiceName', verbose_name='Относится к услуге'),
        ),
    ]
