# Generated by Django 2.2.7 on 2019-11-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='Нет данных', max_length=255, verbose_name='Имя')),
                ('userPhone', models.CharField(default='Нет данных', max_length=255, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Форма заказа звонка',
                'verbose_name_plural': 'Формы заказа звонка',
            },
        ),
    ]
